# Generated by Django 3.2.8 on 2021-10-31 20:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(help_text='Questionnaire created by', on_delete=django.db.models.deletion.PROTECT, related_name='quests_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(help_text='Questionnaire last updated by', on_delete=django.db.models.deletion.PROTECT, related_name='quests_last_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='title of the document', max_length=128)),
                ('content', models.TextField(blank=True, help_text='content of the docuemnt')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(help_text='Document created by', on_delete=django.db.models.deletion.PROTECT, related_name='docs_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(help_text='Document last updated by', on_delete=django.db.models.deletion.PROTECT, related_name='docs_last_updated', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
