# Generated by Django 3.2.8 on 2021-11-01 01:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('repo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='updated_by',
            field=models.ForeignKey(help_text='Document last updated by', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='docs_last_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='updated_by',
            field=models.ForeignKey(help_text='Questionnaire last updated by', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quests_last_updated_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
